import React from 'react';

const teamMembers = [
  {
    name: "Sarah Jenkins",
    role: "Head of Hotel Curation",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Former hospitality executive who knows exactly how to spot genuine value versus clever marketing in hotel listings."
  },
  {
    name: "David Chen",
    role: "Logistics Expert",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Obsessed with efficiency. David tests transfer services and airport assistance programs globally to recommend only the most reliable."
  },
  {
    name: "Elena Rodriguez",
    role: "Digital Nomad & Tech Reviewer",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Travels to 20+ countries a year evaluating eSIM providers for speed, coverage, and hidden data caps."
  }
];

const Team = () => {
  return (
    <section className="py-24 bg-dark-200">
      <div className="container mx-auto px-6 max-w-6xl">
        <div className="text-center mb-16">
          <h2 className="font-serif text-3xl md:text-5xl text-white mb-6">Meet the Deal Hunters</h2>
          <p className="text-gray-400 font-light max-w-2xl mx-auto">
            Our recommendations aren't generated by algorithms. They are handpicked by seasoned travelers who know the industry inside out.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          {teamMembers.map((member, index) => (
            <div key={index} className="group cursor-pointer bg-base rounded-xl overflow-hidden border border-dark-100 hover:border-gold/30 transition-all duration-300">
              <div className="relative overflow-hidden aspect-square">
                <img 
                  src={member.image} 
                  alt={member.name} 
                  className="object-cover w-full h-full transition-transform duration-700 transform group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-base via-base/50 to-transparent opacity-90"></div>
                <div className="absolute bottom-0 left-0 w-full p-6">
                  <p className="text-gold text-xs uppercase tracking-widest font-medium mb-1">{member.role}</p>
                  <h3 className="text-2xl text-white font-serif">{member.name}</h3>
                </div>
              </div>
              <div className="p-6">
                <p className="text-gray-400 font-light text-sm leading-relaxed">{member.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Team;
